from __future__ import annotations

from typing import Protocol

from ai_fund_lab_v2.runtime.runtime_result import RuntimeResult


class RuntimeSchedulerInterface(Protocol):
    def preopen(self) -> RuntimeResult: ...

    def order_prepare(self) -> RuntimeResult: ...

    def submit(self) -> RuntimeResult: ...

    def fill_check(self) -> RuntimeResult: ...

    def monitor(self) -> RuntimeResult: ...

    def close(self) -> RuntimeResult: ...

    def nightly(self) -> RuntimeResult: ...

    def report(self) -> RuntimeResult: ...
